apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-ui
  template:
    metadata:
      labels:
        app: karsajobs-ui
    spec:
      containers:
      - name: karsajobs-ui
        image: ghcr.io/avnanrahman/karsajobs-ui:latest
        resources:
          requests:
            memory: "128Mi" # 128Mi = 128 mebibytes
            cpu: "500m" # 500m = 500 milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80