apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
spec:
  selector:
    app: karsajobs-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
  externalIPs:
    - 172.22.254.39
  nodePort: 30001