apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-ui
  template:
    metadata:
      labels:
        app: karsajobs-ui
    spec:
      containers:
      - name: karsajobs-ui
        image: ghcr.io/avnanrahman/karsajobs-ui:latest
        resources:
          requests:
            memory: "512Mi" # 512Mi = 512 mebibytes
            cpu: "1000m" # 1000m = 1000 milliCPUs (1 CPU)
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80