apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
spec:
  selector:
    app: karsajobs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  externalIPs:
    - 172.22.254.39
  nodePort: 30002