apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv # Nama PersistentVolume
spec:
  storageClassName: manual # Kelas penyimpanan yang digunakan
  capacity:
    storage: 1Gi # Kapasitas penyimpanan yang dialokasikan
  accessModes:
    - ReadWriteOnce # Mode akses: Baca Tulis Sekali
  hostPath:
    path: "/data/db" # Path host di mana volume akan di-mount
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc # Nama PersistentVolumeClaim
  labels:
    app: monggo # Label aplikasi
spec:
  storageClassName: manual # Kelas penyimpanan yang digunakan
  accessModes:
    - ReadWriteOnce # Mode akses: Baca Tulis Sekali
  resources:
    requests:
      storage: 1Gi # Permintaan kapasitas penyimpanan
