apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: monggo
spec:
  selector:
    app: mongo
    tier: data
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30003
  clusterIP: ""