apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=  # Base64 encoded value of "admin"
  mongo-root-password: UGFzc3dvcmRSYWhhc2lhQmFuZ2V0==  # Base64 encoded value of "PasswordRahasiaBanget"