# Nama GitHub Actions Workflow
name: Shipping Service CI

# Set Trigger Github Action
on:
    push:
        branches:
            - shipping-service

jobs:
    shipping:
        name: Build-and-Push

        runs-on: ubuntu-latest

        # Mendeklarasikan langkah-langkah tugas yang akan dijalankan
        steps:
            # Checkout Repo Ke Runner
            - name: checkout-repository
              uses: actions/checkout@v4

            # Install hadolint
            - name: lint-dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: "Dockerfile"

            # Step Build dan Push
            - name: build-and-push
              env:
              # personal access token disimpan pada repository secrets GitHub
                GCR_TOKEN: ${{ secrets.GCR_TOKEN }}
              # Menjalankan script build dan push
              run: |
                export GCR_TOKEN=$GCR_TOKEN
                bash ./build_push_image_shipping.sh


